In [ ]:
import numpy as np #importing the required libraries
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, Activation
from sklearn.preprocessing import StandardScaler
!pip install wwo-hist
from wwo_hist import retrieve_hist_data
import itertools
from sklearn import preprocessing
from math import sqrt
from keras.models import load_model
import requests
import datetime
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
import os,math,time
import keras


#extract the data from api keeping the cities, their date range, api key, frequency of 1 hour, in a form of CSV file
frequency=1
start_date = '1-JAN-2018'
end_date = '31-DEC-2022'
api_key = '###OBTAIN API KEY FROM WWO' # put your api key from wwo, by creating an account
location_list = ["JABALPUR","Vijayawada"]


hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: wwo-hist in /usr/local/lib/python3.10/dist-packages (0.0.7)


Retrieving weather data for JABALPUR


Currently retrieving data for JABALPUR: from 2018-01-01 to 2018-01-31

/usr/local/lib/python3.10/dist-packages/wwo_hist/__init__.py:69: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  list_mon_begin = pd.date_range(start_date, end_date, freq='MS', closed='right')
/usr/local/lib/python3.10/dist-packages/wwo_hist/__init__.py:74: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  list_mon_end = pd.date_range(start_date, end_date, freq='M', closed='left')

Time elapsed (hh:mm:ss.ms) 0:00:01.944944
Currently retrieving data for JABALPUR: from 2018-02-01 to 2018-02-28
Time elapsed (hh:mm:ss.ms) 0:00:05.499850
Currently retrieving data for JABALPUR: from 2018-03-01 to 2018-03-31
Time elapsed (hh:mm:ss.ms) 0:00:09.571843
Currently retrieving data for JABALPUR: from 2018-04-01 to 2018-04-30
Time elapsed (hh:mm:ss.ms) 0:00:11.865425
Currently retrieving data for JABALPUR: from 2018-05-01 to 2018-05-31
Time elapsed (hh:mm:ss.ms) 0:00:14.486126
Currently retrieving data for JABALPUR: from 2018-06-01 to 2018-06-30
Time elapsed (hh:mm:ss.ms) 0:00:16.195803
Currently retrieving data for JABALPUR: from 2018-07-01 to 2018-07-31
Time elapsed (hh:mm:ss.ms) 0:00:18.002731
Currently retrieving data for JABALPUR: from 2018-08-01 to 2018-08-31
Time elapsed (hh:mm:ss.ms) 0:00:21.367275
Currently retrieving data for JABALPUR: from 2018-09-01 to 2018-09-30
Time elapsed (hh:mm:ss.ms) 0:00:23.092207
Currently retrieving data for JABALPUR: from 2018-10-01 to 2018-10-31
Time elapsed (hh:mm:ss.ms) 0:00:26.659694
Currently retrieving data for JABALPUR: from 2018-11-01 to 2018-11-30
Time elapsed (hh:mm:ss.ms) 0:00:28.444331
Currently retrieving data for JABALPUR: from 2018-12-01 to 2018-12-31
Time elapsed (hh:mm:ss.ms) 0:00:31.338706
Currently retrieving data for JABALPUR: from 2019-01-01 to 2019-01-31
Time elapsed (hh:mm:ss.ms) 0:00:33.463216
Currently retrieving data for JABALPUR: from 2019-02-01 to 2019-02-28
Time elapsed (hh:mm:ss.ms) 0:00:35.258491
Currently retrieving data for JABALPUR: from 2019-03-01 to 2019-03-31
Time elapsed (hh:mm:ss.ms) 0:00:37.345702
Currently retrieving data for JABALPUR: from 2019-04-01 to 2019-04-30
Time elapsed (hh:mm:ss.ms) 0:00:39.127835
Currently retrieving data for JABALPUR: from 2019-05-01 to 2019-05-31
Time elapsed (hh:mm:ss.ms) 0:00:41.081882
Currently retrieving data for JABALPUR: from 2019-06-01 to 2019-06-30
Time elapsed (hh:mm:ss.ms) 0:00:42.823188
Currently retrieving data for JABALPUR: from 2019-07-01 to 2019-07-31
Time elapsed (hh:mm:ss.ms) 0:00:44.694934
Currently retrieving data for JABALPUR: from 2019-08-01 to 2019-08-31
Time elapsed (hh:mm:ss.ms) 0:00:46.552365
Currently retrieving data for JABALPUR: from 2019-09-01 to 2019-09-30
Time elapsed (hh:mm:ss.ms) 0:00:48.574780
Currently retrieving data for JABALPUR: from 2019-10-01 to 2019-10-31
Time elapsed (hh:mm:ss.ms) 0:00:50.620546
Currently retrieving data for JABALPUR: from 2019-11-01 to 2019-11-30
Time elapsed (hh:mm:ss.ms) 0:00:53.126552
Currently retrieving data for JABALPUR: from 2019-12-01 to 2019-12-31
Time elapsed (hh:mm:ss.ms) 0:00:54.491935
Currently retrieving data for JABALPUR: from 2020-01-01 to 2020-01-31
Time elapsed (hh:mm:ss.ms) 0:00:56.219289
Currently retrieving data for JABALPUR: from 2020-02-01 to 2020-02-29
Time elapsed (hh:mm:ss.ms) 0:00:58.067267
Currently retrieving data for JABALPUR: from 2020-03-01 to 2020-03-31
Time elapsed (hh:mm:ss.ms) 0:00:59.996413
Currently retrieving data for JABALPUR: from 2020-04-01 to 2020-04-30
Time elapsed (hh:mm:ss.ms) 0:01:01.914280
Currently retrieving data for JABALPUR: from 2020-05-01 to 2020-05-31
Time elapsed (hh:mm:ss.ms) 0:01:03.817994
Currently retrieving data for JABALPUR: from 2020-06-01 to 2020-06-30
Time elapsed (hh:mm:ss.ms) 0:01:05.590853
Currently retrieving data for JABALPUR: from 2020-07-01 to 2020-07-31
Time elapsed (hh:mm:ss.ms) 0:01:09.083361
Currently retrieving data for JABALPUR: from 2020-08-01 to 2020-08-31
Time elapsed (hh:mm:ss.ms) 0:01:11.155567
Currently retrieving data for JABALPUR: from 2020-09-01 to 2020-09-30
Time elapsed (hh:mm:ss.ms) 0:01:12.912643
Currently retrieving data for JABALPUR: from 2020-10-01 to 2020-10-31
Time elapsed (hh:mm:ss.ms) 0:01:15.252548
Currently retrieving data for JABALPUR: from 2020-11-01 to 2020-11-30
Time elapsed (hh:mm:ss.ms) 0:01:16.992195
Currently retrieving data for JABALPUR: from 2020-12-01 to 2020-12-31
Time elapsed (hh:mm:ss.ms) 0:01:18.856953
Currently retrieving data for JABALPUR: from 2021-01-01 to 2021-01-31
Time elapsed (hh:mm:ss.ms) 0:01:20.645785
Currently retrieving data for JABALPUR: from 2021-02-01 to 2021-02-28
Time elapsed (hh:mm:ss.ms) 0:01:22.294232
Currently retrieving data for JABALPUR: from 2021-03-01 to 2021-03-31
Time elapsed (hh:mm:ss.ms) 0:01:25.679465
Currently retrieving data for JABALPUR: from 2021-04-01 to 2021-04-30
Time elapsed (hh:mm:ss.ms) 0:01:27.424178
Currently retrieving data for JABALPUR: from 2021-05-01 to 2021-05-31
Time elapsed (hh:mm:ss.ms) 0:01:29.515669
Currently retrieving data for JABALPUR: from 2021-06-01 to 2021-06-30
Time elapsed (hh:mm:ss.ms) 0:01:31.271757
Currently retrieving data for JABALPUR: from 2021-07-01 to 2021-07-31
Time elapsed (hh:mm:ss.ms) 0:01:32.992750
Currently retrieving data for JABALPUR: from 2021-08-01 to 2021-08-31
Time elapsed (hh:mm:ss.ms) 0:01:34.119478
Currently retrieving data for JABALPUR: from 2021-09-01 to 2021-09-30
Time elapsed (hh:mm:ss.ms) 0:01:35.909169
Currently retrieving data for JABALPUR: from 2021-10-01 to 2021-10-31
Time elapsed (hh:mm:ss.ms) 0:01:37.847227
Currently retrieving data for JABALPUR: from 2021-11-01 to 2021-11-30
Time elapsed (hh:mm:ss.ms) 0:01:39.653492
Currently retrieving data for JABALPUR: from 2021-12-01 to 2021-12-31
Time elapsed (hh:mm:ss.ms) 0:01:41.416876
Currently retrieving data for JABALPUR: from 2022-01-01 to 2022-01-31
Time elapsed (hh:mm:ss.ms) 0:01:43.122043
Currently retrieving data for JABALPUR: from 2022-02-01 to 2022-02-28
Time elapsed (hh:mm:ss.ms) 0:01:44.848233
Currently retrieving data for JABALPUR: from 2022-03-01 to 2022-03-31
Time elapsed (hh:mm:ss.ms) 0:01:46.677330
Currently retrieving data for JABALPUR: from 2022-04-01 to 2022-04-30
Time elapsed (hh:mm:ss.ms) 0:01:48.372866
Currently retrieving data for JABALPUR: from 2022-05-01 to 2022-05-31
Time elapsed (hh:mm:ss.ms) 0:01:50.308845
Currently retrieving data for JABALPUR: from 2022-06-01 to 2022-06-30
Time elapsed (hh:mm:ss.ms) 0:01:52.068358
Currently retrieving data for JABALPUR: from 2022-07-01 to 2022-07-31
Time elapsed (hh:mm:ss.ms) 0:01:53.702075
Currently retrieving data for JABALPUR: from 2022-08-01 to 2022-08-31
Time elapsed (hh:mm:ss.ms) 0:01:55.400553
Currently retrieving data for JABALPUR: from 2022-09-01 to 2022-09-30
Time elapsed (hh:mm:ss.ms) 0:01:57.118575
Currently retrieving data for JABALPUR: from 2022-10-01 to 2022-10-31
Time elapsed (hh:mm:ss.ms) 0:01:58.851759
Currently retrieving data for JABALPUR: from 2022-11-01 to 2022-11-30
Time elapsed (hh:mm:ss.ms) 0:02:00.529215
Currently retrieving data for JABALPUR: from 2022-12-01 to 2022-12-31
Time elapsed (hh:mm:ss.ms) 0:02:02.329334


export JABALPUR completed!




Retrieving weather data for Vijayawada


Currently retrieving data for Vijayawada: from 2018-01-01 to 2018-01-31

/usr/local/lib/python3.10/dist-packages/wwo_hist/__init__.py:69: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  list_mon_begin = pd.date_range(start_date, end_date, freq='MS', closed='right')
/usr/local/lib/python3.10/dist-packages/wwo_hist/__init__.py:74: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  list_mon_end = pd.date_range(start_date, end_date, freq='M', closed='left')

Time elapsed (hh:mm:ss.ms) 0:00:01.831211
Currently retrieving data for Vijayawada: from 2018-02-01 to 2018-02-28
Time elapsed (hh:mm:ss.ms) 0:00:02.999791
Currently retrieving data for Vijayawada: from 2018-03-01 to 2018-03-31
Time elapsed (hh:mm:ss.ms) 0:00:04.693531
Currently retrieving data for Vijayawada: from 2018-04-01 to 2018-04-30
Time elapsed (hh:mm:ss.ms) 0:00:06.594158
Currently retrieving data for Vijayawada: from 2018-05-01 to 2018-05-31
Time elapsed (hh:mm:ss.ms) 0:00:08.488263
Currently retrieving data for Vijayawada: from 2018-06-01 to 2018-06-30
Time elapsed (hh:mm:ss.ms) 0:00:10.320369
Currently retrieving data for Vijayawada: from 2018-07-01 to 2018-07-31
Time elapsed (hh:mm:ss.ms) 0:00:13.711046
Currently retrieving data for Vijayawada: from 2018-08-01 to 2018-08-31
Time elapsed (hh:mm:ss.ms) 0:00:15.542257
Currently retrieving data for Vijayawada: from 2018-09-01 to 2018-09-30
Time elapsed (hh:mm:ss.ms) 0:00:17.500832
Currently retrieving data for Vijayawada: from 2018-10-01 to 2018-10-31
Time elapsed (hh:mm:ss.ms) 0:00:19.234268
Currently retrieving data for Vijayawada: from 2018-11-01 to 2018-11-30
Time elapsed (hh:mm:ss.ms) 0:00:22.468465
Currently retrieving data for Vijayawada: from 2018-12-01 to 2018-12-31
Time elapsed (hh:mm:ss.ms) 0:00:24.405180
Currently retrieving data for Vijayawada: from 2019-01-01 to 2019-01-31
Time elapsed (hh:mm:ss.ms) 0:00:27.860397
Currently retrieving data for Vijayawada: from 2019-02-01 to 2019-02-28
Time elapsed (hh:mm:ss.ms) 0:00:29.563419
Currently retrieving data for Vijayawada: from 2019-03-01 to 2019-03-31
Time elapsed (hh:mm:ss.ms) 0:00:31.478774
Currently retrieving data for Vijayawada: from 2019-04-01 to 2019-04-30
Time elapsed (hh:mm:ss.ms) 0:00:33.145845
Currently retrieving data for Vijayawada: from 2019-05-01 to 2019-05-31
Time elapsed (hh:mm:ss.ms) 0:00:35.025379
Currently retrieving data for Vijayawada: from 2019-06-01 to 2019-06-30
Time elapsed (hh:mm:ss.ms) 0:00:36.924063
Currently retrieving data for Vijayawada: from 2019-07-01 to 2019-07-31
Time elapsed (hh:mm:ss.ms) 0:00:38.158092
Currently retrieving data for Vijayawada: from 2019-08-01 to 2019-08-31
Time elapsed (hh:mm:ss.ms) 0:00:41.264592
Currently retrieving data for Vijayawada: from 2019-09-01 to 2019-09-30
Time elapsed (hh:mm:ss.ms) 0:00:44.775673
Currently retrieving data for Vijayawada: from 2019-10-01 to 2019-10-31
Time elapsed (hh:mm:ss.ms) 0:00:46.655002
Currently retrieving data for Vijayawada: from 2019-11-01 to 2019-11-30
Time elapsed (hh:mm:ss.ms) 0:00:48.448673
Currently retrieving data for Vijayawada: from 2019-12-01 to 2019-12-31
Time elapsed (hh:mm:ss.ms) 0:00:50.500957
Currently retrieving data for Vijayawada: from 2020-01-01 to 2020-01-31
Time elapsed (hh:mm:ss.ms) 0:00:52.293155
Currently retrieving data for Vijayawada: from 2020-02-01 to 2020-02-29
Time elapsed (hh:mm:ss.ms) 0:00:55.939195
Currently retrieving data for Vijayawada: from 2020-03-01 to 2020-03-31
Time elapsed (hh:mm:ss.ms) 0:00:58.322574
Currently retrieving data for Vijayawada: from 2020-04-01 to 2020-04-30
Time elapsed (hh:mm:ss.ms) 0:01:00.144062
Currently retrieving data for Vijayawada: from 2020-05-01 to 2020-05-31
Time elapsed (hh:mm:ss.ms) 0:01:01.967480
Currently retrieving data for Vijayawada: from 2020-06-01 to 2020-06-30
Time elapsed (hh:mm:ss.ms) 0:01:03.733163
Currently retrieving data for Vijayawada: from 2020-07-01 to 2020-07-31
Time elapsed (hh:mm:ss.ms) 0:01:05.394351
Currently retrieving data for Vijayawada: from 2020-08-01 to 2020-08-31
Time elapsed (hh:mm:ss.ms) 0:01:07.209837
Currently retrieving data for Vijayawada: from 2020-09-01 to 2020-09-30
Time elapsed (hh:mm:ss.ms) 0:01:10.408784
Currently retrieving data for Vijayawada: from 2020-10-01 to 2020-10-31
Time elapsed (hh:mm:ss.ms) 0:01:12.426200
Currently retrieving data for Vijayawada: from 2020-11-01 to 2020-11-30
Time elapsed (hh:mm:ss.ms) 0:01:14.162797
Currently retrieving data for Vijayawada: from 2020-12-01 to 2020-12-31
Time elapsed (hh:mm:ss.ms) 0:01:15.938830
Currently retrieving data for Vijayawada: from 2021-01-01 to 2021-01-31
Time elapsed (hh:mm:ss.ms) 0:01:18.606674
Currently retrieving data for Vijayawada: from 2021-02-01 to 2021-02-28
Time elapsed (hh:mm:ss.ms) 0:01:21.435650
Currently retrieving data for Vijayawada: from 2021-03-01 to 2021-03-31
Time elapsed (hh:mm:ss.ms) 0:01:23.199933
Currently retrieving data for Vijayawada: from 2021-04-01 to 2021-04-30
Time elapsed (hh:mm:ss.ms) 0:01:24.998562
Currently retrieving data for Vijayawada: from 2021-05-01 to 2021-05-31
Time elapsed (hh:mm:ss.ms) 0:01:26.755344
Currently retrieving data for Vijayawada: from 2021-06-01 to 2021-06-30
Time elapsed (hh:mm:ss.ms) 0:01:28.498463
Currently retrieving data for Vijayawada: from 2021-07-01 to 2021-07-31
Time elapsed (hh:mm:ss.ms) 0:01:31.513101
Currently retrieving data for Vijayawada: from 2021-08-01 to 2021-08-31
Time elapsed (hh:mm:ss.ms) 0:01:33.286902
Currently retrieving data for Vijayawada: from 2021-09-01 to 2021-09-30
Time elapsed (hh:mm:ss.ms) 0:01:35.017835
Currently retrieving data for Vijayawada: from 2021-10-01 to 2021-10-31
Time elapsed (hh:mm:ss.ms) 0:01:36.903022
Currently retrieving data for Vijayawada: from 2021-11-01 to 2021-11-30
Time elapsed (hh:mm:ss.ms) 0:01:39.777248
Currently retrieving data for Vijayawada: from 2021-12-01 to 2021-12-31
Time elapsed (hh:mm:ss.ms) 0:01:41.507338
Currently retrieving data for Vijayawada: from 2022-01-01 to 2022-01-31
Time elapsed (hh:mm:ss.ms) 0:01:43.696976
Currently retrieving data for Vijayawada: from 2022-02-01 to 2022-02-28
Time elapsed (hh:mm:ss.ms) 0:01:45.339061
Currently retrieving data for Vijayawada: from 2022-03-01 to 2022-03-31
Time elapsed (hh:mm:ss.ms) 0:01:47.043905
Currently retrieving data for Vijayawada: from 2022-04-01 to 2022-04-30
Time elapsed (hh:mm:ss.ms) 0:01:48.870502
Currently retrieving data for Vijayawada: from 2022-05-01 to 2022-05-31
Time elapsed (hh:mm:ss.ms) 0:01:50.805675
Currently retrieving data for Vijayawada: from 2022-06-01 to 2022-06-30
Time elapsed (hh:mm:ss.ms) 0:01:52.517812
Currently retrieving data for Vijayawada: from 2022-07-01 to 2022-07-31
Time elapsed (hh:mm:ss.ms) 0:01:54.278807
Currently retrieving data for Vijayawada: from 2022-08-01 to 2022-08-31
Time elapsed (hh:mm:ss.ms) 0:01:55.978847
Currently retrieving data for Vijayawada: from 2022-09-01 to 2022-09-30
Time elapsed (hh:mm:ss.ms) 0:01:57.694906
Currently retrieving data for Vijayawada: from 2022-10-01 to 2022-10-31
Time elapsed (hh:mm:ss.ms) 0:01:59.487650
Currently retrieving data for Vijayawada: from 2022-11-01 to 2022-11-30
Time elapsed (hh:mm:ss.ms) 0:02:01.285327
Currently retrieving data for Vijayawada: from 2022-12-01 to 2022-12-31
Time elapsed (hh:mm:ss.ms) 0:02:02.998269


export Vijayawada completed!

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Load the historical weather data
data = pd.read_csv('JABALPUR.csv')
data['date_time']=pd.to_datetime(data['date_time'])
datetimedata=data['date_time']

# Select the relevant features for forecasting (temperature, humidity, pressure, etc.)
selected_features = ['WindGustKmph', 'cloudcover', 'humidity', 'precipMM', 'pressure','tempC','visibility','winddirDegree','windspeedKmph']
data = data[selected_features]

# Normalize the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data.values)

In [ ]:
data

,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,8,0,49,0.0,1014,16,10,48,5
1,8,1,49,0.0,1014,16,10,54,5
2,8,1,50,0.0,1014,15,10,61,4
3,8,2,51,0.0,1014,15,10,68,4
4,8,3,49,0.0,1014,15,10,69,5
...,...,...,...,...,...,...,...,...,...
43819,17,2,47,0.0,1017,19,10,241,10
43820,19,1,48,0.0,1017,18,10,137,11
43821,19,0,50,0.0,1018,17,10,33,11
43822,21,0,52,0.0,1018,16,10,33,10
43823,19,1,54,0.0,1018,15,10,33,9

In [ ]:
datetimedata

0       2018-01-01 00:00:00
1       2018-01-01 01:00:00
2       2018-01-01 02:00:00
3       2018-01-01 03:00:00
4       2018-01-01 04:00:00
                ...
43819   2022-12-31 19:00:00
43820   2022-12-31 20:00:00
43821   2022-12-31 21:00:00
43822   2022-12-31 22:00:00
43823   2022-12-31 23:00:00
Name: date_time, Length: 43824, dtype: datetime64[ns]

In [ ]:
# Define the number of previous time steps to consider
lookback = 30

# Prepare the data for training
X_train, y_train = [], []
for i in range(len(scaled_data) - lookback - 24):
    X_train.append(scaled_data[i:i+lookback])
    y_train.append(scaled_data[i+lookback:i+lookback+24])
X_train, y_train = np.array(X_train), np.array(y_train)

# Build the LSTM model
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(lookback, len(selected_features))))
model.add(LSTM(units=50))
model.add(Dense(units=24 * len(selected_features)))  # Output layer for the next 24 hours
model.compile(optimizer='adam', loss='mean_squared_error')
y_train = y_train.reshape(-1, 24 * len(selected_features))
# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)

# Get the last lookback time steps from the training data
last_sequence = scaled_data[-lookback:]

# Prepare the input for forecasting
X_forecast = []
X_forecast.append(last_sequence)
X_forecast = np.array(X_forecast)

# Make the forecast
forecast = model.predict(X_forecast)

# Reshape the forecasted data
forecast = forecast.reshape(24, len(selected_features))

# Inverse scaling for the forecasted data
forecast = scaler.inverse_transform(forecast)

# Create a time index for the forecasted hours

Epoch 1/10
1368/1368 [==============================] - 35s 23ms/step - loss: 0.4286
Epoch 2/10
1368/1368 [==============================] - 33s 24ms/step - loss: 0.3509
Epoch 3/10
1368/1368 [==============================] - 31s 23ms/step - loss: 0.3249
Epoch 4/10
1368/1368 [==============================] - 32s 23ms/step - loss: 0.3047
Epoch 5/10
1368/1368 [==============================] - 32s 23ms/step - loss: 0.2900
Epoch 6/10
1368/1368 [==============================] - 32s 23ms/step - loss: 0.2773
Epoch 7/10
1368/1368 [==============================] - 32s 23ms/step - loss: 0.2660
Epoch 8/10
1368/1368 [==============================] - 32s 24ms/step - loss: 0.2571
Epoch 9/10
1368/1368 [==============================] - 31s 23ms/step - loss: 0.2486
Epoch 10/10
1368/1368 [==============================] - 32s 23ms/step - loss: 0.2416
1/1 [==============================] - 1s 663ms/step

In [ ]:
datetimedata

0       2018-01-01 00:00:00
1       2018-01-01 01:00:00
2       2018-01-01 02:00:00
3       2018-01-01 03:00:00
4       2018-01-01 04:00:00
                ...
43819   2022-12-31 19:00:00
43820   2022-12-31 20:00:00
43821   2022-12-31 21:00:00
43822   2022-12-31 22:00:00
43823   2022-12-31 23:00:00
Name: date_time, Length: 43824, dtype: datetime64[ns]

In [ ]:
datetimedata.index[-1]

43823

In [ ]:
last_date = pd.to_datetime(datetimedata.iloc[-1])
forecast_index = pd.date_range(start=last_date + pd.DateOffset(hours=1), periods=24, freq='H')

# Display the forecasted weather for the next 24 hours
forecast_df = pd.DataFrame(forecast, columns=selected_features, index=forecast_index)
forecast_df

,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
2023-01-01 00:00:00,15.494897,6.620857,54.357784,0.022420,1016.609131,14.070683,9.933773,30.052055,7.432325
2023-01-01 01:00:00,14.603076,6.832731,55.405319,0.000182,1016.388367,13.303618,9.893559,28.625313,6.931940
2023-01-01 02:00:00,13.473322,6.269833,56.469791,-0.013616,1016.179077,12.653180,9.747156,35.242043,6.266909
2023-01-01 03:00:00,11.996951,5.871077,57.191105,-0.013908,1016.127930,12.193549,9.655372,41.838661,5.530798
2023-01-01 04:00:00,10.515557,4.709326,57.240864,-0.000904,1016.263855,11.924830,9.595670,49.314247,4.989891
2023-01-01 05:00:00,9.221984,3.418701,56.605534,-0.003423,1016.547546,11.919402,9.642751,55.909157,4.533093
2023-01-01 06:00:00,8.327042,2.363640,55.032257,-0.035682,1017.035278,12.590684,9.704441,67.582253,4.295669
2023-01-01 07:00:00,7.988403,1.619158,52.273834,-0.051893,1017.449463,13.866381,9.802767,82.908211,4.385374
2023-01-01 08:00:00,8.195785,1.030167,48.495182,-0.047831,1017.705872,15.555717,9.908176,103.748978,4.833184
2023-01-01 09:00:00,9.100132,0.886915,44.145794,-0.049484,1017.751587,17.636461,9.983355,128.949265,5.409644
2023-01-01 10:00:00,10.252588,0.685284,39.521317,-0.052273,1017.394104,19.870934,10.012186,156.402985,6.192882
2023-01-01 11:00:00,11.670008,0.414778,35.357071,-0.046725,1016.745911,21.983332,10.000193,186.957916,6.903080
2023-01-01 12:00:00,12.841647,0.386431,32.312134,-0.029236,1015.882202,23.665947,9.945635,213.899094,7.488431
2023-01-01 13:00:00,13.801464,0.420841,30.752995,-0.000431,1015.053101,24.672083,9.873063,237.943085,8.077589
2023-01-01 14:00:00,14.376415,0.985819,30.736528,0.017029,1014.284546,24.964643,9.814170,254.180695,8.311477
2023-01-01 15:00:00,14.537683,0.719410,31.901903,0.012344,1013.887329,24.659395,9.792283,259.806396,8.290520
2023-01-01 16:00:00,14.155436,0.832334,34.084755,-0.000468,1013.784058,23.731276,9.807569,251.444397,8.013851
2023-01-01 17:00:00,13.697090,-0.129458,36.694008,0.012547,1014.050110,22.569366,9.857232,234.631180,7.691504
2023-01-01 18:00:00,13.316969,-0.161753,39.413105,0.009271,1014.650635,21.149364,9.939695,210.764542,7.348576
2023-01-01 19:00:00,13.331121,0.029825,41.815525,-0.006621,1015.345764,19.726994,10.031952,182.918259,7.092309
2023-01-01 20:00:00,13.440375,-0.076796,43.718880,-0.044786,1016.010376,18.463417,10.099714,155.443924,6.996102
2023-01-01 21:00:00,13.658808,-0.067600,45.085426,-0.090390,1016.583923,17.445955,10.157220,130.378311,6.920188
2023-01-01 22:00:00,13.789420,-0.111282,46.106857,-0.115148,1016.820435,16.590359,10.183051,110.815125,6.860116
2023-01-01 23:00:00,13.667676,0.134453,46.875824,-0.133945,1016.830139,15.588035,10.174237,96.401611,6.692132

In [ ]:
model.save('Jabalpur.h5')

In [ ]:
#import the required libraries

import numpy as np #importing the required libraries
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, Activation
from sklearn.preprocessing import StandardScaler
!pip install wwo-hist
from wwo_hist import retrieve_hist_data
import itertools
from sklearn import preprocessing
from math import sqrt
from keras.models import load_model
import requests
import datetime
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
import os,math,time
import keras
from datetime import date,timedelta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting wwo-hist
  Downloading wwo_hist-0.0.7-py3-none-any.whl (4.6 kB)
Installing collected packages: wwo-hist
Successfully installed wwo-hist-0.0.7

In [ ]:
#extract the data from api keeping the cities, their date range, api key, frequency of 1 hour, in a form of CSV file
now = date.today()
tomorrow=now + timedelta(1)
now=now.strftime("%d-%b-%Y") #make today date as string
tomorrow=tomorrow.strftime("%d-%b-%Y") #take tomorrow date as string
#it contains hourly data of Jabalpur city and we're extracting the information from wwo
frequency=1
start_date = now
end_date = tomorrow
api_key = '###api key'
location_list = ["JABALPUR"] #same procedure with mentioning the upcoming date....


hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True) #extract past information

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense


name=input("Enter the name in Capital letters:")
names=name+'.csv'

Retrieving weather data for JABALPUR


Currently retrieving data for JABALPUR: from 2023-06-20 to 2023-06-21

/usr/local/lib/python3.10/dist-packages/wwo_hist/__init__.py:69: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  list_mon_begin = pd.date_range(start_date, end_date, freq='MS', closed='right')
/usr/local/lib/python3.10/dist-packages/wwo_hist/__init__.py:74: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  list_mon_end = pd.date_range(start_date, end_date, freq='M', closed='left')

Time elapsed (hh:mm:ss.ms) 0:00:00.278028


export JABALPUR completed!


Enter the name in Capital letters:JABALPUR

In [ ]:
names

'JABALPUR.csv'

In [ ]:
# Load the historical weather data
data = pd.read_csv(names)
data= data.tail(120)
data['date_time']=pd.to_datetime(data['date_time'])
datetimedata=data['date_time']

# Select the relevant features for forecasting (temperature, humidity, pressure, etc.)
selected_features = ['WindGustKmph', 'cloudcover', 'humidity', 'precipMM', 'pressure','tempC','visibility','winddirDegree','windspeedKmph']
data = data[selected_features]

# Normalize the data
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data.values)

#load the model
model = keras.models.load_model('/content/Jabalpur.h5')
# Restore the weights

lookback = 30
# Prepare the data for training
X_train, y_train = [], []
for i in range(len(scaled_data) - lookback - 24):
    X_train.append(scaled_data[i:i+lookback])
    y_train.append(scaled_data[i+lookback:i+lookback+24])
X_train, y_train = np.array(X_train), np.array(y_train)

y_train = y_train.reshape(-1, 24 * len(selected_features))
# Train the model

# Get the last lookback time steps from the training data

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 30, 50)            12000

 lstm_1 (LSTM)               (None, 50)                20200

 dense (Dense)               (None, 216)               11016

=================================================================
Total params: 43,216
Trainable params: 43,216
Non-trainable params: 0
_________________________________________________________________

In [ ]:
last_sequence = scaled_data[-lookback:]

# Prepare the input for forecasting
X_forecast = []
X_forecast.append(last_sequence)
X_forecast = np.array(X_forecast)

# Make the forecast
forecast = model.predict(X_forecast)

# Reshape the forecasted data
forecast = forecast.reshape(24, len(selected_features))

# Inverse scaling for the forecasted data
forecast = scaler.inverse_transform(forecast)

# Create a time index for the forecasted hours
last_date = pd.to_datetime(datetimedata.iloc[-1])
forecast_index = pd.date_range(start=last_date + pd.DateOffset(hours=1), periods=24, freq='H')

# Display the forecasted weather for the next 24 hours
forecast_df = pd.DataFrame(forecast, columns=selected_features, index=forecast_index)
forecast_df

# Evaluate the model

1/1 [==============================] - 1s 642ms/step

,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
2023-06-22 00:00:00,14.714503,15.231480,56.664932,0.015089,1001.953247,31.169029,9.899258,296.546356,9.875494
2023-06-22 01:00:00,15.026234,12.118835,56.301281,0.014152,1001.861206,31.367493,9.931558,296.541229,10.513556
2023-06-22 02:00:00,15.386208,13.905503,55.678074,0.008300,1001.790405,31.394587,9.950285,291.405426,10.981352
2023-06-22 03:00:00,15.404508,9.962279,55.759811,0.009420,1001.669312,31.546736,9.944264,285.257141,11.234224
2023-06-22 04:00:00,15.676552,10.773991,54.744904,0.005622,1001.526733,31.740173,9.966661,283.292480,11.374557
2023-06-22 05:00:00,14.913980,11.705854,54.112171,0.001792,1001.543213,31.657280,9.993269,279.939514,11.385731
2023-06-22 06:00:00,14.220723,13.591610,52.831100,-0.000837,1001.546265,31.570148,9.998078,274.895935,11.444212
2023-06-22 07:00:00,14.521025,11.634401,50.825130,-0.000588,1001.695068,31.910519,9.979718,271.881989,11.725176
2023-06-22 08:00:00,14.292767,9.663849,48.186630,0.000691,1002.006714,32.404396,10.004622,270.334930,11.936018
2023-06-22 09:00:00,15.288490,12.132339,46.025059,-0.002190,1001.927979,32.916199,10.031429,266.543365,12.174402
2023-06-22 10:00:00,15.624144,10.603894,42.499817,0.001158,1002.027710,33.676498,10.026284,272.071564,13.038079
2023-06-22 11:00:00,16.700359,13.223148,39.415333,-0.000582,1001.871338,34.383354,10.047570,278.587097,13.752377
2023-06-22 12:00:00,18.221504,14.552253,36.801430,0.006297,1001.709045,35.011314,10.059294,289.038422,14.895103
2023-06-22 13:00:00,19.321501,14.465025,35.394619,0.003398,1001.500122,35.471130,10.043043,299.220367,15.335735
2023-06-22 14:00:00,19.793419,16.169558,34.486870,0.010133,1001.211670,35.452847,10.075703,308.292084,15.453703
2023-06-22 15:00:00,20.470013,15.443019,34.857109,0.008177,1000.968872,35.303223,10.059045,316.736328,15.051830
2023-06-22 16:00:00,20.019056,18.292398,35.762177,0.009190,1000.826904,34.979500,10.044316,317.768127,14.907620
2023-06-22 17:00:00,18.805887,15.700398,38.784092,0.006342,1000.845886,34.171734,10.023565,315.941925,13.450558
2023-06-22 18:00:00,17.451269,16.500755,41.207298,0.008153,1001.090149,33.421677,10.014748,312.581390,12.211432
2023-06-22 19:00:00,16.285614,14.566263,43.399128,0.006585,1001.206055,32.461147,10.026883,303.631836,11.080825
2023-06-22 20:00:00,15.268186,11.606843,45.469360,0.005356,1001.562622,31.978043,10.045986,294.419647,10.615946
2023-06-22 21:00:00,15.135199,11.113432,47.193195,0.008336,1001.780762,31.396465,10.039989,283.673889,10.197094
2023-06-22 22:00:00,14.948188,9.661339,49.184780,0.006566,1002.041504,31.149595,10.050163,274.358368,9.893780
2023-06-22 23:00:00,14.990770,6.554985,49.418549,0.015005,1002.100952,31.082581,10.054835,270.662292,9.832335